### TEST it

GET https://101.95.95.28/m_departmentid.html
Cookie: sessidssl=42FACE410DC769C19E74113A3596133A;path=/;secure



### test login
POST https://101.95.95.28/checkLogin.cgi
Content-Type: application/x-www-form-urlencoded

i0023=7654321&i0025=7654321



### download
GET http://101.95.95.27/wcd/download_f.html

